### ISSUE TITLE
handleClick

### ISSUE THREAD

**Issue by safadig** [TheSmiths-Widgets/ts.prettymenu#4]
Can you please state which typo? Still getting the error

**Comment by KtorZ** [comment]
The object `Ti.API` doesn't not contain any `alert` method; The `alert` method is in the global context so has to be called directly. 

Look at the related commit @85b4e157 for the correction and be a bit autonomous :)

**Comment by safadig** [comment]
Thx. I was just looking at wrong area. ..very simple :-)
